name = "globaltimepro-cf"
compatibility_date = "2026-02-02"
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_SITE_URL = "https://www.globaltimepro.com"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-BF82Z0DFTG"
NEXT_PUBLIC_MS_CLARITY_ID = "r6hqg7q0iv"
NEXT_PUBLIC_GTM_ID = "GTM-T4PV48VB"
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAB_XHltEXcejoBIy"
